# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 6
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.cache/wt [current_project]
set_property parent.project_path /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/nasti/nasti_request.vh
read_verilog -library xil_defaultlib -sv {
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/peripheral/AXIMem.sv
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/peripheral/AXIMmio.sv
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/peripheral/DTModule.sv
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/utils/nasti_lite_bridge.sv
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/utils/nasti_lite_reader.sv
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/utils/nasti_lite_writer.sv
}
read_verilog -library xil_defaultlib {
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/AsyncResetReg.v
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/EICG_wrapper.v
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/components_DefaultFPGAConfig.behav_srams.v
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/components_DefaultFPGAConfig.v
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/plusarg_reader.v
  /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/imports/rocket_neutrino/rocketTop.v
}
read_ip -quiet /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xci
set_property used_in_implementation false [get_files -all /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xdc]
set_property is_locked true [get_files /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/constrs_1/imports/rocket_neutrino/pinMap.xdc
set_property used_in_implementation false [get_files /home/neutrino/vivado_work/rocket_v0.1/rocket_v0.1.srcs/constrs_1/imports/rocket_neutrino/pinMap.xdc]


synth_design -top rocketTop -part xc7a100tcsg324-1


write_checkpoint -force -noxdef rocketTop.dcp

catch { report_utilization -file rocketTop_utilization_synth.rpt -pb rocketTop_utilization_synth.pb }
